---
- name: Loading secrets
  include_vars: "secrets.yml"

- name: Logging into Docker Registry
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Acquiring Nexus image
  docker_image:
     name: "{{ docker_registry }}/{{ nexus_image_name }}"
     state: "present"

- name: Checking if Nexus data folder exists
  file:
    path: "{{ nexus_data }}"
    state: "directory"

- name: Start up Nexus Docker container
  docker_container:
    name: "nexus"
    image: "{{ docker_registry }}/{{ nexus_image_name }}"
    detach: yes
    state: started
    exposed_ports: "[ {{ nexus_port }} ]"
    privileged: no
    volumes:
      - "{{ nexus_data }}:{{ nexus_data }}"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"