---
#- name: Loading secrets
#  include_vars: "{{ playbook_dir }}/vars/secrets.yml"

- name: Installing Docker
  yum:
    name: docker-latest
    state: present
#  when: ansible_virtualization_type != "docker"

- name: Starting the Docker service
  systemd:
    name: docker
    enabled: "True"
    state: "started"
#  when: ansible_virtualization_type != "docker"

- name: Logging into Docker Registry
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"

- name: Acquiring Nexus image
  docker_image:
     name: "{{ docker_registry }}/{{ nexus_image_name }}"
     state: "present"

- name: Checking if Nexus data folder exists
  file:
    path: "{{ nexus_data }}"
    state: "directory"

- name: Start up Nexus Docker container
  docker_container:
    name: "nexus"
    image: "{{ docker_registry }}/{{ nexus_image_name }}"
    detach: yes
    state: started
    exposed_ports: "[ {{ nexus_port }} ]"
    privileged: no
    volumes:
      - "{{ nexus_data }}:{{ nexus_data }}"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"