---
- name: Logging into Docker Registry
  docker_login:
    registry: "{{ nexus_registry }}"
    username: "{{ nexus_registry_username }}"
    password: "{{ nexus_registry_password }}"
  when: nexus_registry_login == true

- name: Pulling Nexus image
  docker_image:
     name: "{{ nexus_registry }}/{{ nexus_image_name }}"
     state: present

- name: Starting up the Nexus container using a data volume
  docker_service:
    state: present
    project_name: nexus
    definition:
      version: '2'
      services:
        nexus3:
          image: "{{ nexus_registry }}/{{ nexus_image_name }}"
          ports:
            - "{{ nexus_port }}"
          volumes:
            - "{{ nexus_data }}:/{{ nexus_data }}"
  become: yes
  register: output

- debug:
    var: output
...
