---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: nexus
    image: centos:7
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
#    command:
#      - sh
#      - -c
#      - /opt/sonatype/start-nexus-repository-manager.sh
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
#    - idempotence
#    - lint
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
