---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create
      include_tasks: "docker.yml"

- name: Converge
  hosts: all
  pre_tasks:
    - name: Set yum cache to "keep"
      replace:
        dest: /etc/yum.conf
        regexp:  'keepcache=(.*)'
        replace: 'keepcache=1'
    - name: Loading secrets
      include_vars: "{{ playbook_dir }}/vars/secrets.yml"
  roles:
    - role: nexus_install_application
...
